spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: "jdbc:mariadb://localhost:3306/ossProject?characterEncoding=UTF-8&serverTimezone=UTC"
    username: root
    password: 1q2w3e4r!

